"""research/select_top_factors.py — 从 IC 候选池按 IC/ICIR 选 top-N 因子，写因子配置 YAML。

ridge 在 67 个量价 alpha 因子上 multicollinearity 严重，喂前 30 个 IC/ICIR
最高的因子通常优于全量。本脚本读 IC 摘要 CSV + 候选池 JSON，按 ICIR（或
IC 均值）降序排，取 top-N，写 `run.py --factor-config` 期望的 YAML。

用法::

    python -m research.select_top_factors \
        --pool research/output/selected_factors_h5_barra_pure.json \
        --ic   research/output/ic_summary_h5_barra_pure.csv \
        --by icir --top 30 \
        --out  research/output/factor_configs_h5_top30.yaml
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parent.parent


def _load_pool(pool_path: Path) -> tuple[int, list[str]]:
    with pool_path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    horizon = int(data.get("horizon", 5))
    factors = list(data.get("factors", []))
    if not factors:
        raise ValueError(f"候选池 {pool_path} 的 'factors' 字段为空")
    return horizon, factors


def _load_ic(ic_path: Path) -> pd.DataFrame:
    df = pd.read_csv(ic_path)
    # 列名兼容：因子 / factor
    if "因子" in df.columns:
        df = df.rename(columns={"因子": "factor"})
    if "factor" not in df.columns:
        raise ValueError(f"IC 摘要 {ic_path} 缺少 '因子'/'factor' 列，实际列={list(df.columns)}")
    return df


def _horizon_to_rebalance_freq(horizon: int) -> str:
    if horizon <= 3:
        return "3D"
    if horizon <= 7:
        return "W-FRI"
    if horizon <= 15:
        return "2W-FRI"
    return "ME"


def select_top_factors(
    pool_path: Path,
    ic_path: Path,
    by: str = "icir",
    top: int = 30,
) -> tuple[int, pd.DataFrame, list[str]]:
    horizon, candidates = _load_pool(pool_path)
    ic = _load_ic(ic_path)

    # 仅在 IC 摘要里出现的候选因子才参与排序（候选池可能含 Barra/regime，但
    # 这些不在 alpha 候选范围内；IC 摘要里没有的候选因子跳过）
    ic = ic[ic["factor"].isin(candidates)].copy()
    if ic.empty:
        raise ValueError(
            f"IC 摘要 {ic_path} 与候选池 {pool_path} 无公共因子；"
            f"候选池前 5: {candidates[:5]}"
        )

    sort_col = "ICIR" if by == "icir" else "IC均值"
    if sort_col not in ic.columns:
        raise ValueError(
            f"IC 摘要缺少排序列 '{sort_col}'，实际列={list(ic.columns)}；"
            f"by 可选: ic / icir"
        )
    ic[sort_col] = pd.to_numeric(ic[sort_col], errors="coerce")
    ic = ic.dropna(subset=[sort_col]).sort_values(sort_col, ascending=False).reset_index(drop=True)

    # ICIR 排序时按 ICIR 降序；IC 排序时按 |IC| 降序（因子方向已在函数内取反，
    # 但 IC 摘要里可能保留原始符号，取绝对值排序更稳）
    if by == "ic":
        ic["__abs"] = ic[sort_col].abs()
        ic = ic.sort_values("__abs", ascending=False).drop(columns="__abs").reset_index(drop=True)

    picked = ic.head(top).copy()
    selected = picked["factor"].tolist()
    return horizon, picked, selected


def write_yaml(out_path: Path, horizon: int, selected: list[str]) -> None:
    cfg = {
        f"h{horizon}": {
            "horizon": horizon,
            "rebalance_freq": _horizon_to_rebalance_freq(horizon),
            "factors": selected,
        }
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write(f"# Top-{len(selected)} factors for h{horizon}, generated by research/select_top_factors.py\n")
        yaml.safe_dump(cfg, f, allow_unicode=True, sort_keys=False)
    print(f"写入 {out_path}（h{horizon}, {len(selected)} 个因子）")


def main() -> None:
    p = argparse.ArgumentParser(description="按 IC/ICIR 从候选池选 top-N 因子并写 YAML")
    p.add_argument("--pool", default="research/output/selected_factors_h5_barra_pure.json",
                   help="候选池 JSON（含 factors 列表）")
    p.add_argument("--ic", default="research/output/ic_summary_h5_barra_pure.csv",
                   help="IC 摘要 CSV（含 因子/ICIR/IC均值 列）")
    p.add_argument("--by", choices=["ic", "icir"], default="icir",
                   help="排序依据：icir（默认）或 ic（按 |IC| 降序）")
    p.add_argument("--top", type=int, default=30, help="选取前 N 个因子（默认 30）")
    p.add_argument("--out", default="research/output/factor_configs_h5_top30.yaml",
                   help="输出 YAML 路径")
    args = p.parse_args()

    pool_path = (ROOT / args.pool) if not Path(args.pool).is_absolute() else Path(args.pool)
    ic_path = (ROOT / args.ic) if not Path(args.ic).is_absolute() else Path(args.ic)
    out_path = (ROOT / args.out) if not Path(args.out).is_absolute() else Path(args.out)

    horizon, picked, selected = select_top_factors(pool_path, ic_path, args.by, args.top)

    print(f"\n=== Top {len(selected)} factors (by {args.by}, h{horizon}) ===")
    cols = ["factor", "ICIR", "IC均值"] if "ICIR" in picked.columns else ["factor", "IC均值"]
    show = picked[cols].copy()
    show.insert(0, "rank", range(1, len(show) + 1))
    print(show.to_string(index=False))

    write_yaml(out_path, horizon, selected)


if __name__ == "__main__":
    main()
