"""
logs/driver.py — 自动化实验流水线

IC 分析 + 因子筛选 → 写入 factor_configs.yaml → 模型训练 + 回测

用法:
    # 完整流程（IC h5/h20 + 写 YAML + 主力 ensemble 实验）
    python logs/driver.py --preset main

    # 只做 IC 分析并同步 YAML（不过夜跑模型）
    python logs/driver.py --ic-only --horizons 5,20 --barra --lookback-years 3

    # 跳过 IC，用现有 YAML 跑消融实验
    python logs/driver.py --skip-ic --preset ablation

    # 自定义单条实验
    python logs/driver.py --skip-ic --run ensemble:20 --models lgbm,xgb --blend-dynamic

    # 跑完后汇总 model_metrics / backtest 结果
    python logs/driver.py --skip-ic --preset main --analyze

预设 (--preset):
    main      — ensemble lgbm+xgb + blend-dynamic，h5 + h20（当前最佳实践）
    ablation  — ridge/lgbm/xgb/cat/ensemble × h5/h20（driver5 风格）
    dynamic   — dynamic + 短窗口 ensemble w6-12（driver6 风格）
    ic-full   — 仅 IC 分析 h5/h10/h20，全样本 + 近3年（driver_ic 风格）
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE))

from config.encoding_bootstrap import bootstrap_stdio_utf8, utf8_subprocess_env

bootstrap_stdio_utf8()
LOG_DIR = BASE / "logs"
OUTPUT_DIR = BASE / "research" / "output"
YAML_PATH = BASE / "config" / "factor_configs.yaml"

if sys.platform == "win32":
    DEFAULT_PY = BASE / ".venv" / "Scripts" / "python.exe"
else:
    DEFAULT_PY = BASE / ".venv" / "bin" / "python"


def _horizon_to_rebalance_freq(horizon: int) -> str:
    if horizon <= 3:
        return "3D"
    if horizon <= 7:
        return "W-FRI"
    if horizon <= 15:
        return "2W-FRI"
    return "ME"


def sync_factor_yaml(
    horizons: list[int],
    yaml_path: Path = YAML_PATH,
    json_dir: Path = OUTPUT_DIR,
) -> Path:
    """将 selected_factors_h{N}.json 合并写入 factor_configs.yaml。"""
    try:
        import yaml
    except ImportError:
        raise SystemExit("缺少 PyYAML，请运行: pip install pyyaml")

    cfg: dict = {}
    if yaml_path.exists():
        cfg = yaml.safe_load(yaml_path.read_text(encoding="utf-8")) or {}

    updated = []
    for h in horizons:
        json_path = json_dir / f"selected_factors_h{h}.json"
        if not json_path.exists():
            print(f"[driver] 跳过 h{h}: 未找到 {json_path}", flush=True)
            continue
        sel = json.loads(json_path.read_text(encoding="utf-8"))
        key = f"h{h}"
        cfg[key] = {
            "horizon": h,
            "rebalance_freq": _horizon_to_rebalance_freq(h),
            "factors": sel.get("factors", []),
            "excluded": sel.get("excluded", {}),
        }
        if sel.get("lookback_years") not in (None, "full", 0):
            cfg[key]["lookback_years"] = sel["lookback_years"]
        if sel.get("ic_start_date"):
            cfg[key]["ic_start_date"] = sel["ic_start_date"]
        # Dual-whitelist fields (engine v2): Gram-Schmidt orthogonal factor list
        # and its config meta. Only written when present in the JSON so older
        # h10/h20 sections (no factors_orth) stay unchanged.
        if sel.get("factors_orth"):
            cfg[key]["factors_orth"] = sel["factors_orth"]
        if sel.get("orthogonalization"):
            cfg[key]["orthogonalization"] = sel["orthogonalization"]
        # 稀疏轨入选（corr-dedup 后）；供 --sparse-from-ic / 文档对照，不进 factors 主白名单
        if sel.get("factors_sparse"):
            cfg[key]["factors_sparse"] = sel["factors_sparse"]
        updated.append(key)

    if not updated:
        raise SystemExit("[driver] 没有可同步的 IC 结果，请先运行 IC 分析")

    header = (
        f"# Auto-generated by logs/driver.py sync "
        f"({datetime.now():%Y-%m-%d %H:%M})\n"
    )
    yaml_path.parent.mkdir(parents=True, exist_ok=True)
    yaml_path.write_text(
        header + yaml.dump(cfg, allow_unicode=True, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )
    print(f"[driver] 已更新 {yaml_path}，键: {updated}", flush=True)
    return yaml_path


def run_cmd(cmd: list[str], log_out: Path, log_err: Path | None = None) -> int:
    log_out.parent.mkdir(parents=True, exist_ok=True)
    err_path = log_err or log_out.with_suffix(log_out.suffix + ".err")
    print(f"[driver] START: {' '.join(cmd)}", flush=True)
    with open(log_out, "w", encoding="utf-8") as fo, \
         open(err_path, "w", encoding="utf-8") as fe:
        p = subprocess.Popen(
            cmd, stdout=fo, stderr=fe, cwd=BASE, env=utf8_subprocess_env(),
        )
        rc = p.wait()
    status = "OK" if rc == 0 else f"FAIL(rc={rc})"
    print(f"[driver] DONE:  {status}  log={log_out.name}", flush=True)
    return rc


def run_ic(
    py: str,
    horizon: int,
    barra: bool = True,
    lookback_years: int = 0,
    tag_suffix: str = "",
) -> int:
    # Canonical IC: --barra --save；FDR / t=2.5 / corr-dedup 为 CLI 默认。
    # Gram-Schmidt 默认 OFF（需 --gram-schmidt 显式开启）。
    # workers=1 显式压内存（与 settings 并行建议一致）。
    cmd = [
        py, "-m", "research.ic_analysis_v2",
        "--period", str(horizon),
        "--save",
        "--workers", "1", "--barra-workers", "1",
    ]
    if barra:
        cmd.append("--barra")
    if lookback_years > 0:
        cmd.extend(["--lookback-years", str(lookback_years)])
    tag = f"ic_h{horizon}{tag_suffix}"
    return run_cmd(cmd, LOG_DIR / f"{tag}.log")


@dataclass
class Experiment:
    mode: str
    horizon: int
    train_windows: str | None = None   # e.g. "6,12"
    models: str | None = None          # e.g. "lgbm,xgb"
    blend_dynamic: bool = False
    tag: str | None = None

    def build_cmd(
        self, py: str, yaml: str, skip_download: bool = True,
        output_dir: str | None = None,
    ) -> tuple[list[str], str]:
        cmd = [py, "run.py", "--mode", self.mode, "--horizon", str(self.horizon)]
        if skip_download:
            cmd.append("--skip-download")
        cmd.extend(["--factor-config", yaml])
        if self.train_windows:
            cmd.extend(["--train-windows", self.train_windows])
        if self.models:
            cmd.extend(["--models", self.models])
        if self.blend_dynamic:
            cmd.append("--blend-dynamic")
        if output_dir:
            cmd.extend(["--output-dir", output_dir])

        tag = self.tag or self._default_tag()
        return cmd, tag

    def _default_tag(self) -> str:
        parts = [self.mode, f"h{self.horizon}"]
        if self.train_windows:
            parts.append(f"w{self.train_windows.replace(',', '-')}")
        if self.models:
            parts.append(f"m{self.models.replace(',', '-')}")
        if self.blend_dynamic:
            parts.append("blend")
        return "_".join(parts)


PRESETS: dict[str, list[Experiment]] = {
    "main": [
        Experiment("ensemble", 5,  models="lgbm,xgb", blend_dynamic=True),
        Experiment("ensemble", 20, models="lgbm,xgb", blend_dynamic=True),
    ],
    "ablation": [
        Experiment("ensemble", 5),
        Experiment("ensemble", 20),
        Experiment("ridge",    5),
        Experiment("ridge",    20),
        Experiment("lgbm",     5),
        Experiment("lgbm",     20),
        Experiment("xgb",      5),
        Experiment("xgb",      20),
        Experiment("cat",      5),
        Experiment("cat",      20),
    ],
    "dynamic": [
        Experiment("dynamic",  5),
        Experiment("dynamic",  20),
        Experiment("ensemble", 5,  train_windows="6,12"),
        Experiment("ensemble", 20, train_windows="6,12"),
    ],
}


def parse_run_spec(spec: str) -> Experiment:
    """解析 'ensemble:20' 或 'dynamic:5' 格式。"""
    mode, _, h = spec.partition(":")
    if not h.isdigit():
        raise ValueError(f"无效 --run 格式: {spec}，应为 mode:horizon")
    return Experiment(mode=mode, horizon=int(h))


def run_ic_batch(
    py: str,
    horizons: list[int],
    barra: bool,
    lookback_years: int,
    parallel: bool,
) -> dict[str, int]:
    results = {}
    if parallel and len(horizons) > 1:
        procs = []
        for h in horizons:
            suffix = f"_lb{lookback_years}" if lookback_years else "_full"
            cmd = [
                py, "-m", "research.ic_analysis_v2",
                "--period", str(h),
                "--save",
                "--workers", "1", "--barra-workers", "1",
            ]
            if barra:
                cmd.append("--barra")
            if lookback_years > 0:
                cmd.extend(["--lookback-years", str(lookback_years)])
            tag = f"ic_h{h}{suffix}"
            log = LOG_DIR / f"{tag}.log"
            log.parent.mkdir(parents=True, exist_ok=True)
            print(f"[driver] PARALLEL START: h{h}", flush=True)
            with open(log, "w", encoding="utf-8") as fo, \
                 open(log.with_suffix(".err.log"), "w", encoding="utf-8") as fe:
                p = subprocess.Popen(
                    cmd, stdout=fo, stderr=fe, cwd=BASE, env=utf8_subprocess_env(),
                )
            procs.append((f"h{h}", p, log))
        for name, p, log in procs:
            rc = p.wait()
            results[name] = rc
            print(f"[driver] PARALLEL DONE: {name} rc={rc} log={log.name}", flush=True)
    else:
        suffix = f"_lb{lookback_years}" if lookback_years else ""
        for h in horizons:
            results[f"h{h}"] = run_ic(py, h, barra=barra, lookback_years=lookback_years,
                                      tag_suffix=suffix)
    return results


def main():
    parser = argparse.ArgumentParser(description="IC 分析 → YAML → 模型实验 自动化流水线")
    parser.add_argument("--python", default=str(DEFAULT_PY), help="Python 解释器路径")
    parser.add_argument("--yaml", default=str(YAML_PATH), help="factor_configs.yaml 路径")

    ic_grp = parser.add_argument_group("IC 分析")
    ic_grp.add_argument("--ic-only", action="store_true", help="只跑 IC + 写 YAML，不训练模型")
    ic_grp.add_argument("--skip-ic", action="store_true", help="跳过 IC，直接用现有 YAML/JSON")
    ic_grp.add_argument("--horizons", default="5,20", help="IC 持仓期，逗号分隔，如 5,10,20")
    ic_grp.add_argument("--barra", action="store_true", default=True,
                        help="IC 分析启用 Barra 纯因子（默认开启）")
    ic_grp.add_argument("--no-barra", action="store_true", help="IC 分析不用 Barra")
    ic_grp.add_argument("--lookback-years", type=int, default=0,
                        help="IC 筛选只看近 N 年（0=全历史）")
    ic_grp.add_argument("--parallel-ic", action="store_true", help="多 horizon IC 并行")

    run_grp = parser.add_argument_group("模型实验")
    run_grp.add_argument("--preset", choices=[*PRESETS.keys(), "ic-full"],
                         help="实验预设")
    run_grp.add_argument("--run", action="append", dest="runs",
                         help="自定义实验 mode:horizon，可重复")
    run_grp.add_argument("--train-windows", help="覆盖 --run 的训练窗口，如 6,12")
    run_grp.add_argument("--models", help="覆盖 --run 的模型列表，如 lgbm,xgb")
    run_grp.add_argument("--blend-dynamic", action="store_true",
                         help="覆盖 --run：ML + dynamic rank-average")
    run_grp.add_argument("--output-dir", help="实验输出目录，如 results/v5_window612_h5/")
    run_grp.add_argument("--no-skip-download", action="store_true",
                         help="实验时允许触发数据下载")

    parser.add_argument("--analyze", action="store_true",
                        help="全部完成后运行 logs/analyze_results.py")
    args = parser.parse_args()

    py = args.python
    yaml = args.yaml
    horizons = [int(x.strip()) for x in args.horizons.split(",") if x.strip()]
    barra = args.barra and not args.no_barra

    if not Path(py).exists():
        raise SystemExit(f"Python 不存在: {py}，请先创建虚拟环境")

    # ── IC 分析 ──────────────────────────────────────────────────────────────
    if not args.skip_ic:
        if args.preset == "ic-full":
            # driver_ic 风格：全样本 + 近3年，h5/h10/h20
            ic_horizons = [5, 10, 20]
            for lb in (0, 3):
                print(f"\n[driver] === IC batch lookback={'full' if lb == 0 else lb}y ===",
                      flush=True)
                run_ic_batch(py, ic_horizons, barra, lb, args.parallel_ic)
            sync_factor_yaml(ic_horizons, Path(yaml))
        else:
            run_ic_batch(py, horizons, barra, args.lookback_years, args.parallel_ic)
            sync_factor_yaml(horizons, Path(yaml))

        if args.ic_only:
            print("[driver] --ic-only 完成", flush=True)
            return

    # ── 模型实验 ─────────────────────────────────────────────────────────────
    experiments: list[Experiment] = []
    if args.runs:
        for spec in args.runs:
            exp = parse_run_spec(spec)
            if args.train_windows:
                exp.train_windows = args.train_windows
            if args.models:
                exp.models = args.models
            if args.blend_dynamic:
                exp.blend_dynamic = True
            experiments.append(exp)
    elif args.preset and args.preset != "ic-full":
        experiments = PRESETS[args.preset]
    elif not args.skip_ic:
        # 默认：IC 完成后跑 main 预设
        experiments = PRESETS["main"]
    else:
        raise SystemExit("请指定 --preset、--run，或去掉 --skip-ic 使用默认 main 预设")

    skip_dl = not args.no_skip_download
    results = {}
    for exp in experiments:
        cmd, tag = exp.build_cmd(py, yaml, skip_download=skip_dl,
                                 output_dir=args.output_dir)
        rc = run_cmd(cmd, LOG_DIR / f"run_{tag}.log", LOG_DIR / f"run_{tag}_err.log")
        results[tag] = rc

    print(f"\n[driver] 实验汇总: {results}", flush=True)

    if args.analyze:
        analyze_script = LOG_DIR / "analyze_results.py"
        run_cmd([py, str(analyze_script)], LOG_DIR / "analyze_results.log")

    failed = [k for k, v in results.items() if v != 0]
    if failed:
        raise SystemExit(f"[driver] 以下实验失败: {failed}")
    print("[driver] ALL DONE", flush=True)


if __name__ == "__main__":
    main()
